"""auto migration 2025-12-19T11:56:34.617660+00:00

Revision ID: 577ca5075e2b
Revises: a71eb11e5acb
Create Date: 2025-12-19 12:56:34.826428

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "577ca5075e2b"
down_revision: Union[str, Sequence[str], None] = "a71eb11e5acb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "providers", sa.Column("value_min", sa.Numeric(precision=12, scale=4), nullable=True)
    )
    op.add_column(
        "providers", sa.Column("value_max", sa.Numeric(precision=12, scale=4), nullable=True)
    )
    op.drop_column("providers", "min_value")
    op.drop_column("providers", "model")
    op.drop_column("providers", "polling_interval_sec")
    op.drop_column("providers", "max_value")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "providers",
        sa.Column(
            "max_value", sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "providers",
        sa.Column("polling_interval_sec", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column("providers", sa.Column("model", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(
        "providers",
        sa.Column(
            "min_value", sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("providers", "value_max")
    op.drop_column("providers", "value_min")
    # ### end Alembic commands ###
